# Generated by Django 3.2.6 on 2022-01-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POD_NAME', models.CharField(max_length=225)),
                ('CPU_USAGE', models.IntegerField()),
                ('RAM_USAGE', models.IntegerField()),
                ('TIME_STAMP', models.CharField(max_length=225)),
            ],
        ),
    ]
