# Generated by Django 3.2.6 on 2022-01-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceUsage',
            new_name='EP_ENGINE_USAGE',
        ),
    ]
